### ISSUE TITLE
ndoutils 2.1.3 hanging randomly with Nagios XI 5.4.11

### ISSUE THREAD

**Issue by Rfferrao87** [NagiosEnterprises/ndoutils#48]
Hello Team,

We've been facing a problem with this Nagios server which currently has up to 3k hosts and 13k services (on average), and we can't figure out if it is related to ndo2db or not. Lately everytime we start the services, the status_update_time column in nagios_programstatus is about 2 minutes early and, after a while, it starts catching up to real time. The problem is that, out of the blue, it just hangs for 2, 3 or even 5 minutes and NagVis complains and stops working.

Just a quick note, the time for both Nagios and the dedicated DB server are synchronized perfectly and their specs are 4x CPU and 32 GB RAM for the Nagios XI server and 4x CPU and 8GB RAM for the DB server.

I'm kind of a noob in this overall platform, so I apologize in advance for any slip-ups or lack of information. Any help and/or insight would be very much appreciated!

Thank you very much!

Best regards.

**Comment by box293** [comment]
Could we please get you to log this in our support forum:
https://support.nagios.com/forum/index.php
Customer Support or General Support has a **Nagios XI** section.

More forum information:
https://support.nagios.com/kb/category.php?id=59

If you have support contract you can also create a ticket.
https://support.nagios.com/kb/article/creating-a-ticket-in-the-support-center-769.html

I suspect your problem is related to:
https://support.nagios.com/kb/article/ndoutils-message-queue-exceeded-139.html

Any further troubleshooting steps should be continued in the forums or support ticket.

Thank You

**Comment by Rfferrao87** [comment]
I'm pretty sure the "message queue exceeded" article just solved the issue for us. Thank you so much for the feedback! Spot on!

Best regards.
