### ISSUE TITLE
Increase output column length

### ISSUE THREAD

**Issue by tatref** [NagiosEnterprises/ndoutils#54]
From the nagios source code, the plugin output may take up to 8192 bytes:
https://github.com/NagiosEnterprises/nagioscore/blob/a7346f7d630813536ff42f7daa8ad2afd24139f4/include/nagios.h#L280

However, the `output `column inthe `servicestatus `table is only 255 bytes:
https://github.com/NagiosEnterprises/ndoutils/blob/c115d3dea3b1040c67d287671486a82a6af55ced/db/mysql.sql#L1199

The same issue exists for the `hostsatus `table

Is it possible to bump the size to match the nagios values?

**Comment by hedenface** [comment]
These are set pretty conservatively for a reason - specifically because `output` is defined as the first line of output. The `long_output` should have the full body (after the first line). See: http://nagios-plugins.org/doc/guidelines.html#AEN33

All that being said, if you're running into some actual limitation, I'd look over a report - but in the meantime, just updating your own installation to meet these requirements would work best.
