### ISSUE TITLE
State History does not use actual plugin long_output

### ISSUE THREAD

**Issue by ssaxnagios** [NagiosEnterprises/ndoutils#8]
When you get a state change and it puts the data into the nagios_statehistory table it is using the untruncated plugin output when it should be using the plugin long_output.

**Comment by abrist** [comment]
I belive that decision was made to help reduce the overall size of the table. Also, both plugin_output and long_output would need to be included,  add the first line of the status output is not included in long_output.

**Comment by jfrickson** [comment]
Fixed in commits:
https://github.com/NagiosEnterprises/ndoutils/commit/5e488140fa38655427cd93338aaaf4f7762147de
https://github.com/NagiosEnterprises/nagioscore/commit/54ec85154fbbea268b9ad30de9d7a01db02278c2
in branches:
https://github.com/NagiosEnterprises/ndoutils/tree/ndoutils-2.1b2
https://github.com/NagiosEnterprises/nagioscore/tree/nagios-4.1.2-Pre1
